### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by fuodorov** [Xomakk/Shift_test_case#1]
@Xomakk 

1. Где `Readme` файл?
2. Нужно убрать каталог `.idea`
3. Добавить `.gitignore` file
4. Поощрается соблюдать PEP и использовать линтеры, например: `black` `flake8` `isort` `pylint`. Рекомендую добавить конфиги для каждого.
5. Обычно добавляют `.env.example` со списком нужных переменных для запуска (вместо оригинального `.env`)
6. Все комментарии в коде лучше убрать (например в `alembic.ini`). Пользы от них мало)
7. `DATABASE_URL = f"postgresql+asyncpg://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}"` можно повысить читаемость кода, используя `.format()` для строк такого характера
8. Очень хорошо, что используешь `type hinting`, однако тогда будь добр использовать его везде (так как хуже нетипизированного кода может быть только наполовину типизированный код :) и подключить какой-либо анализатор кода, например `mypy`.
9. `from src.config import DB_HOST, DB_NAME, DB_PASS, DB_PORT, DB_USER` советую заменить на что-то такое `from src import config as cfg`. Это повысит читаемость кода и будет проще импортировать +100500 настроек
10. Не помешало бы добавить версионирование API
11. `access_token = Column(String, nullable=False, default=lambda: str(uuid.uuid4), index=True)` - если поле `uuid`, то оно должно быть типом `uuid`, а не стринг. То же самое касается и остальных полей
12. Айдишники лучше делать `uuid`
13. `verify_password` я бы убрал туда, где у тебя лежит бизнес логика.
14. Связь юзера и токена должна быть 1:m, а не 1:1.
15. Если переменную используешь один раз, ее можно дополнительно неинициализировать. Например,     
```
#salary = result.scalars().first()
#    return salary

return result.scalars().first()
```
17. Всегда настроженно отношусь, когда вижу методы `.first()` и `.last()`
18. `access_token = str(uuid.uuid4())` - возможно это не лучший способ генерить токены
19. функция `check_token` не подразумевает под собой удаление токена из бд :)
20. `status_code=400` вместо циферок лучше использовать модуль `status`
21. При желании можно добавить логирование )

**Comment by Xomakk** [comment]
```
(venv) PS C:\Users\ily30\OneDrive\Рабочий стол\test_case_SHIFT> mypy .
src\database.py:18: error: No overload variant of "sessionmaker" matches argument types "AsyncEngine", "Type[AsyncSession]", "bool"  [call-overload]
src\database.py:18: note: Possible overload variants:
src\database.py:18: note:     def [_S <: Session] sessionmaker(self, bind: Union[Engine, Connection, None] = ..., *, class_: Type[_S], autoflush: bool = ..., expire_on_commit: bool = ..., info: Optional[Dict[Any, Any]] = ..., **kw: Any) -> sessionmaker[_S]
src\database.py:18: note:     def [_S <: Session] sessionmaker(self, bind: Union[Engine, Connection, None] = ..., *, autoflush: bool = ..., expire_on_commit: bool = ..., info: Optional[Dict[Any, Any]] = ..., **kw: Any) -> sessionmaker[Session]
Found 1 error in 1 file (checked 14 source files)
(venv) PS C:\Users\ily30\OneDrive\Рабочий стол\test_case_SHIFT> 
```



не получается исправить одну ошибки от mypy. 

Связана c функцией создания двигателя sessionmaker из sqlalchemy. Он работает с асинхронным движком, но типизация похоже в этой функции стоит на синхронный.

**Comment by Xomakk** [comment]
> 14. Связь юзера и токена должна быть 1:m, а не 1:1.

что тогда происходит со старым токеном в БД после релогина? Просто остается?

> 18. access_token = str(uuid.uuid4()) - возможно это не лучший способ генерить токены

какой вариант лучше?) Библиотека какая-то под эти цели есть?

> 19. функция check_token не подразумевает под собой удаление токена из бд :)

т.е. нужно переименовать в protected или что-то подобное, или разделить логику на 2 функции? Вообще можно и изменение сделать, но все упирается в вопрос что делать со старыми токенами в БД

**Comment by fuodorov** [comment]
> ```
> (venv) PS C:\Users\ily30\OneDrive\Рабочий стол\test_case_SHIFT> mypy .
> src\database.py:18: error: No overload variant of "sessionmaker" matches argument types "AsyncEngine", "Type[AsyncSession]", "bool"  [call-overload]
> src\database.py:18: note: Possible overload variants:
> src\database.py:18: note:     def [_S <: Session] sessionmaker(self, bind: Union[Engine, Connection, None] = ..., *, class_: Type[_S], autoflush: bool = ..., expire_on_commit: bool = ..., info: Optional[Dict[Any, Any]] = ..., **kw: Any) -> sessionmaker[_S]
> src\database.py:18: note:     def [_S <: Session] sessionmaker(self, bind: Union[Engine, Connection, None] = ..., *, autoflush: bool = ..., expire_on_commit: bool = ..., info: Optional[Dict[Any, Any]] = ..., **kw: Any) -> sessionmaker[Session]
> Found 1 error in 1 file (checked 14 source files)
> (venv) PS C:\Users\ily30\OneDrive\Рабочий стол\test_case_SHIFT> 
> ```
> 
> не получается исправить одну ошибки от mypy.
> 
> Связана c функцией создания двигателя sessionmaker из sqlalchemy. Он работает с асинхронным движком, но типизация похоже в этой функции стоит на синхронный.

Значит надо искать их асинхронные аналоги - https://github.com/sqlalchemy/sqlalchemy/issues/9126 )

**Comment by fuodorov** [comment]
> что тогда происходит со старым токеном в БД после релогина? Просто остается?

я имел в виду, что юзер может использовать несколько клиентов/устройств для входа одновременно, а поэтому 1:n 


> какой вариант лучше?) Библиотека какая-то под эти цели есть?

например, `secrets` - https://docs.python.org/3/library/secrets.html#generating-tokens


> т.е. нужно переименовать в protected или что-то подобное, или разделить логику на 2 функции? Вообще можно и изменение сделать, но все упирается в вопрос что делать со старыми токенами в БД

намекал на отдельную функцию - `revoke_token`, старые токены - удалять, а что с ними еще делать? :)

**Comment by Xomakk** [comment]
>я имел в виду, что юзер может использовать несколько клиентов/устройств для входа одновременно, а поэтому 1:n

получается при вызове check_token по хорошему должны проверяться все токены, которые привязаны к юзеру?
Если он 2 раза отправит запрос на логин с одного и того же устройства, ему сгенерится 2 разных токена же. Последний он, например, предъявляет, пока срок не истечет. А второй получается просто в БД висит, пока его не отправят на проверку. Как быть?

**Comment by Xomakk** [comment]
Есть еще 2 ошибки одинаковые, с которыми не понимаю как справиться.

```
(venv) PS C:\Users\ily30\OneDrive\Рабочий стол\test_case_SHIFT> mypy .
src\salary\utils.py:32: error: Incompatible types in assignment (expression has type "int", variable has type "Column[int]")  [assignment]
src\salary\utils.py:33: error: Incompatible types in assignment (expression has type "datetime", variable has type "Column[datetime]")  [assignment]
Found 2 errors in 1 file (checked 14 source files)
(venv) PS C:\Users\ily30\OneDrive\Рабочий стол\test_case_SHIFT> 
```

обе они в функции edit_user_salary из файла src\salary\utils.py. Я у объекта salary ORM модели изменяю свойство, которое имеет тип Column[int], на значение типа int. А как их привести к одному то? На Column[int] в схеме pydantic ругается

```
from datetime import datetime

from pydantic import BaseModel


class SalaryBase(BaseModel):
    size: int # <- если тут поставить Column[int] начинает ругаться pydantic
    increase_date: datetime

    class Config:
        orm_mode = True


class SalaryEdit(SalaryBase):
    pass
```

**Comment by fuodorov** [comment]
> > я имел в виду, что юзер может использовать несколько клиентов/устройств для входа одновременно, а поэтому 1:n
> 
> получается при вызове check_token по хорошему должны проверяться все токены, которые привязаны к юзеру? Если он 2 раза отправит запрос на логин с одного и того же устройства, ему сгенерится 2 разных токена же. Последний он, например, предъявляет, пока срок не истечет. А второй получается просто в БД висит, пока его не отправят на проверку. Как быть?

Пусть висит - это не такая большая проблема) Решается примитивно - крон задачей на удаление протухших токенов

**Comment by fuodorov** [comment]
> Есть еще 2 ошибки одинаковые, с которыми не понимаю как справиться.
> 
> ```
> (venv) PS C:\Users\ily30\OneDrive\Рабочий стол\test_case_SHIFT> mypy .
> src\salary\utils.py:32: error: Incompatible types in assignment (expression has type "int", variable has type "Column[int]")  [assignment]
> src\salary\utils.py:33: error: Incompatible types in assignment (expression has type "datetime", variable has type "Column[datetime]")  [assignment]
> Found 2 errors in 1 file (checked 14 source files)
> (venv) PS C:\Users\ily30\OneDrive\Рабочий стол\test_case_SHIFT> 
> ```
> 
> обе они в функции edit_user_salary из файла src\salary\utils.py. Я у объекта salary ORM модели изменяю свойство, которое имеет тип Column[int], на значение типа int. А как их привести к одному то? На Column[int] в схеме pydantic ругается
> 
> ```
> from datetime import datetime
> 
> from pydantic import BaseModel
> 
> 
> class SalaryBase(BaseModel):
>     size: int # <- если тут поставить Column[int] начинает ругаться pydantic
>     increase_date: datetime
> 
>     class Config:
>         orm_mode = True
> 
> 
> class SalaryEdit(SalaryBase):
>     pass
> ```

сильно не вчитывался, но вроде то, что надо - https://docs.sqlalchemy.org/en/20/orm/extensions/mypy.html

**Comment by Xomakk** [comment]
> 10. Не помешало бы добавить версионирование API

Для версионирования что еще нужно добавить, кроме /v1.0 в пути?

**Comment by fuodorov** [comment]
> > 10. Не помешало бы добавить версионирование API
> 
> Для версионирования что еще нужно добавить, кроме /v1.0 в пути?

Желательно это отразить еще в структуре проекта, например, так:

```
- auth
- - api
- - - v1
- - - - router.py
```
